[build]
  base    = "frontend"
  command = "npm install --prefix ../backend && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  directory = "../backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
